pipeline:
  build:
    image: golang:${GO_VERSION}
    commands:
      - go build
      - go test

  push:
    image: plugins/docker
    repo: choestelus/fortnight
    tags: ${DRONE_TAG##v}
    build_args:
      - GO_VERSION=${GO_VERSION}
    secrets: [docker_username, docker_password]
    when:
      event:
        exclude: deployment
      matrix:
        GO_VERSION: 1.9-alpine

  deploy:
    image: vallard/drone-kube
    template: drone-deployment.yml
    namespace: default
    server: https://192.168.99.100:8443
    secrets: [KUBE_TOKEN, KUBE_CA, KUBE_SERVER]
    when:
      event: [tag, deployment]
      matrix:
        GO_VERSION: 1.9-alpine

matrix:
  GO_VERSION:
    - 1.9
    - 1.9-alpine
