pipeline:
  build:
    image: golang:${GO_VERSION}
    commands:
      - go build
      - go test

  push:
    image: plugins/docker
    repo: choestelus/fortnight
    tags: ${GO_VERSION}
    build_args:
      - GO_VERSION=${GO_VERSION}
    secrets: [docker_username, docker_password]
    when:
      matrix:
        GO_VERSION: 1.9-alpine

matrix:
  GO_VERSION:
    - 1.9
    - 1.9-alpine
