pipeline:
  build:
    image: golang:${GO_VERSION}
    commands:
      - go build
      - go test

  push:
    image: plugins/docker
    repo: choestelus/fortnight
    tags: latest
    secrets: [docker_username, docker_password]
    when:
      matrix:
        GO_VERSION: [latest, 1.9]

matrix:
  GO_VERSION:
    - latest
    - 1.9
    - 1.8
