apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: fortnight
  name: fortnight-deployment
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 5
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      app: fortnight
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: fortnight
    spec:
      containers:
      - image: choestelus/fortnight:latest
        imagePullPolicy: IfNotPresent
        name: fortnight
        ports:
        - containerPort: 9000
          protocol: TCP
        resources: {}
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
